{
 "title": "Prefect Deployment Infos",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "deployment_name",
    "label": "Deployment",
    "query": {
     "query": "label_values(prefect_info_deployment,deployment_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"$deployment_name\" && (name!=\"POST\" && name!=\"HEAD\" && name!=\"GET\" && name!~\"start\" && name!~\"shutdown.*\")}",
     "spss": 3,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Logoutput ",
   "type": "stat",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (severity) (count_over_time({ job = \"$deployment_name\" } | json [$__auto]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{job=\"$deployment_name\"} | json |  line_format \"{{ .severity }} {{ .resources_service_version }} {{ .body }}\""
    }
   ]
  }
 ]
}