networks:
  dev_env:
    name: dev_env
    external: true

services:

  qdrant-v2:
    image: qdrant/qdrant:latest
    container_name: qdrant-masterarbeit-v02
    privileged: true
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "6335:6333"
      - "6336:6334"
    volumes:
      - ./disks/qdrant-data-masterarbeit:/qdrant/storage
    restart: always
    networks:
      - dev_env
    healthcheck:
      test:
        - CMD-SHELL
        - bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  neo4j-v2:
    image: neo4j
    container_name: neo4j-masterarbeit-v02
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./disks/neo4j/data:/data
      - ./disks/neo4j/logs:/logs
      - ./disks/neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: "${NEO4J_USER}/${NEO4J_PASSWORD}"       
      NEO4J_PLUGINS: '["apoc","graph-data-science"]'
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_dbms_memory_heap_initial__size: 2g
      NEO4J_dbms_memory_heap_max__size: 2g
    restart: always
    networks:
      - dev_env
    healthcheck:
      test: ["CMD-SHELL", "bash -c ':> /dev/tcp/127.0.0.1/7687' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
