networks:
  dev_env:
    name: dev_env
    external: true

services:
  file-uploader-prefrect-v02:
    image: file-uploader-prefect:v02
    container_name: file-uploader-prefrect-masterarbeit-v02
    restart: unless-stopped
    networks:
      - dev_env
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_SECRETS: ${LOG_SECRETS}
      S3_HOST: ${S3_HOST}
      S3_ACCESS_KEY: ${MINIO_USER}
      S3_SECRET_KEY: ${MINIO_PASSWORD}
      S3_SESSION_KEY: ${S3_SESSION_KEY}
      S3_IS_SECURE: ${S3_IS_SECURE}
      OTEL_HOST: ${OTEL_HOST}
      OTEL_ENABLED: ${OTEL_ENABLED}
      OTEL_INSECURE: ${OTEL_INSECURE}
      PREFECT_API_URL: ${PREFECT_API_URL}
      OBSERVE_DIR: ${OBSERVE_DIR}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      FILE_TYPES_TO_OBSERVE: ${FILE_TYPES_TO_OBSERVE}
    volumes:
      - ./files:/app/api/file-uploader-prefect/src/files
  file-converter-prefrect-v02:
    image: file-converter-prefect:v02
    container_name: file-converter-prefrect-masterarbeit-v02
    restart: unless-stopped
    networks:
      - dev_env
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_SECRETS: ${LOG_SECRETS}
      FILE_CONVERTER_API: ${FILE_CONVERTER_API}
      PREFECT_API_URL: ${PREFECT_API_URL}
      OTEL_HOST: ${OTEL_HOST}
      OTEL_ENABLED: ${OTEL_ENABLED}
      OTEL_INSECURE: ${OTEL_INSECURE}
      S3_HOST: ${S3_HOST}
      S3_ACCESS_KEY: ${MINIO_USER}
      S3_SECRET_KEY: ${MINIO_PASSWORD}
      S3_SESSION_KEY: ${S3_SESSION_KEY}
      S3_IS_SECURE: ${S3_IS_SECURE}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      OPENAI_HOST: ${OPENAI_HOST}
      OPENAI_MODEL: ${IMAGE_MODEL}
    volumes:
      - ./prompts:/app/api/file-converter-prefect/src/prompts
